lists/urls.py
from django.conf.urls import url

from lists import views

urlpatterns = [
    # url(r'^$', views.home_page, name='home'),
    # url(r'^lists/new$', views.new_list, name='new_list'),
    # url(r'^lists/(\d+)/$', views.view_list, name='view_list'),
    # url(r'^lists/(\d+)/add_item$', views.add_item, name='add_item'),
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
    # url(r'^lists/(.+)/$', 'lists.views.view_list', name='view_list'),
    # url(r'^admin/', include(admin.site.urls)),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    # url(r'^lists/new$', views.new_list, name='new_list'),
    # url(r'^lists/(\d+)/$', views.view_list, name='view_list'),
    # url(r'^lists/(\d+)/add_item$', views.add_item, name='add_item'),
    # url(r'^lists/(.+)/$', 'lists.views.view_list', name='view_list'),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models

# Create your models here.

class List(models.Model):
    pass

class Item(models.Model):
    number = models.IntegerField(default=0)
    guessnumber = models.IntegerField(default=0)
    result = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect, render
from lists.models import Item, List
from random import randint

# Create your views here.

def home_page(request):
      items = Item.objects.all()
      itemsCount = Item.objects.count()
      comment = 'yey, waktunya berlibur'

      return render(request, 'home.html', {'comment': comment})

def view_list(request, list_id):
      list_ = List.objects.get(id=list_id)
      komentar = comment(list_)

      return render(request, 'list.html', {'list': list_, 'komentar': komentar})

def new_list(request):
      list_ = List.objects.create()

      number = randint(1,30)
      guessnumber = int(request.POST['item_text'])

      item = Item()
      item.number = number
      item.guessnumber = guessnumber
      item.result = game_result(number, guessnumber)
      item.list = list_
      item.save()
      
      return redirect('/lists/%d/' % (list_.id,))

def add_item(request, list_id):
      list_ = List.objects.get(id=list_id)
      
      number = randint(1,30)
      guessnumber = int(request.POST['item_text'])

      item = Item()
      item.number = number
      item.guessnumber = guessnumber
      item.result = game_result(number, guessnumber)
      item.list = list_
      item.save()

      return redirect('/lists/%d/' % (list_.id,)) 

def game_result(num, gnum):
      range1 = num - 2
      range2 = num + 2

      if gnum > range1 and gnum < range2:
           return 'Kamu menang!!'
      else:
           return 'Kamu kalah!!'

def comment(list_num):
      list_temp =  Item.objects.filter(list=list_num).reverse()
      counter = 0
      komen = ''

      if len(list_temp) < 3:
         return komen

      for i in range(3):
          item = list_temp[i]
          if item.result == 'Kamu menang!!':
               counter = counter +1
    
      if counter == 3:
           komen = 'Ulala'

      if len(list_temp) < 5:
         return komen
      
      counter = 0
      
      for i in range(5):
          item = list_temp[i]
          if item.result == 'Kamu menang!!':
               counter = counter +1
    
      if counter == 5:
           komen = 'Ulalala'

      if len(list_temp) < 10:
           return komen

      counter = 0
      
      for i in range(10):
          item = list_temp[i]
          if item.result == 'Kamu menang!!':
               counter = counter +1
    
      if counter == 10:
           komen = 'Uulala'

      return komen

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>To-Do lists</title>
	    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	    <link href="/static/base.css" rel="stylesheet">
	</head>

	<body>
	    <div class="container">

		    <div class="row">
		        <div class="col-md-6 col-md-offset-3">
		            <div class="text-center">
		                <h2>{% block header_text %}{% endblock %}</h2>
		                <form method="POST" action="{% block form_action %}{% endblock %}">
		                    <input name="item_text" id="id_new_item" class="form-control" placeholder="Masukan angka tebakan"/>
		                    {% csrf_token %}
		                </form>
		            </div>
		        </div>
		    </div>

		    <div class="row">
		        <div class="col-md-6 col-md-offset-3">

		            {% block table %}
		            {% endblock %}
		        </div>
		    </div>

		</div>
	</body>
</html>

lists/templates/home.html
<html>
	<head>
    	<title>Game Tebak Angka</title>
    </head>
    <body>
    	{% extends 'base.html' %}

    	<!-- <h1>Start a new To-Do list</h1> -->
    	{% block header_text %}Game Tebak Angka{% endblock %}
    	<!-- <form method="POST" action="/lists/new"> -->
    	<form method="POST" action="{% block form_action %}/lists/new{% endblock %}">
        	<input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
        	{% csrf_token %}
    	</form>
	</body>
</html>

lists/templates/list.html
<html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
        {% extends 'base.html' %}

        <!-- <h1>Your To-Do list</h1> -->
        {% block header_text %}Game Tebak Angka{% endblock %}
        <!-- <form method="POST" action="/lists/{{ list.id }}/add_item"> -->
        <form method="POST" action="{% block form_action %}/lists/{{ list.id }}/add_item{% endblock %}">
            <input name="item_text" id="id_new_item" placeholder="Enter a to-do item" />
            {% csrf_token %}
        </form>


        {% block table %}
            <table id="id_list_table" class="table">
                {% for item in list.item_set.all %}
                    <tr>
                        <td>
                            Angka: {{ item.number }}, Tebakan: {{ item.guessnumber }} <br>
                            {{ item.result }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
                    <span id='komentar'>{{ komentar }}</span>

        {% endblock %}
    </body>
</html>